version: "3.3"

services:
  mongo_db:
    image: mongo:4.2
    container_name: db_container
    volumes:
      - mongo_db:/data/db/
    restart: always

  server:
    build: ./server
    container_name: app_server
    image: api_server:1.0.0
    volumes:
      - ./server:/code
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - mongo_db

  client:
    container_name: app_client
    image: api_client:1.0.0
    build:
      context: client
      target: production
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - server

volumes:
  mongo_db: {}
