version: "3.2"

services:
  client:
    container_name: app_client
    image: api_client:1.0.0
    build:
      context: .
      target: production
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: always


