version: "3.1"

services:
  mongo_db:
    image: mongo:4.2
    container_name: db_container
    volumes:
      - mongo_db:/data/db
    restart: always

  server:
    build: ./server
    container_name: compose_server
    volumes:
      - ./server:/code
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - mongo_db

  client:
    build: ./client
    container_name: compose_client
    volumes:
      - ./client:/app
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - server

volumes:
  mongo_db: {}
